// Node helpers for scripts: sign in with SRP via amazon-cognito-identity-js and call AppSync.
import Cognito from "amazon-cognito-identity-js";
import * as fs from "node:fs";
import * as path from "node:path";
import { pathToFileURL } from "node:url";

const { CognitoUserPool, CognitoUser, AuthenticationDetails } = Cognito;

/** Load web/js/config.js (generated by deploy) with env-var overrides. */
export async function loadConfig() {
  const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..", "..");
  const cfgPath = path.join(root, "web", "js", "config.js");
  let cfg = {};
  if (fs.existsSync(cfgPath)) cfg = (await import(pathToFileURL(cfgPath).href)).config;
  return {
    region: process.env.TRYOUT_REGION || cfg.region || "ca-central-1",
    userPoolId: process.env.TRYOUT_USER_POOL_ID || cfg.userPoolId,
    userPoolClientId: process.env.TRYOUT_CLIENT_ID || cfg.userPoolClientId,
    graphqlUrl: process.env.TRYOUT_GRAPHQL_URL || cfg.graphqlUrl,
    appUrl: process.env.TRYOUT_APP_URL || cfg.appUrl,
  };
}

/** Resolves to the Cognito ID token (JWT). */
export function signIn({ userPoolId, userPoolClientId }, email, password) {
  const pool = new CognitoUserPool({ UserPoolId: userPoolId, ClientId: userPoolClientId });
  const user = new CognitoUser({ Username: email, Pool: pool });
  const details = new AuthenticationDetails({ Username: email, Password: password });
  return new Promise((resolve, reject) => {
    user.authenticateUser(details, {
      onSuccess: (session) => resolve(session.getIdToken().getJwtToken()),
      onFailure: reject,
      newPasswordRequired: () => reject(new Error("Account still has a temporary password; sign in once in the browser first")),
    });
  });
}

export async function gql(graphqlUrl, idToken, query, variables = {}) {
  const res = await fetch(graphqlUrl, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: idToken },
    body: JSON.stringify({ query, variables }),
  });
  const body = await res.json();
  if (body.errors?.length) throw new Error(body.errors.map((e) => e.message).join("; "));
  return body.data;
}
