// Node helpers for scripts: sign in with email + password via the Cognito USER_AUTH flow (plain fetch) and call AppSync.
import * as fs from "node:fs";
import * as path from "node:path";
import { pathToFileURL } from "node:url";

/** Load web/js/config.js (generated by deploy) with env-var overrides. */
export async function loadConfig() {
  const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..", "..");
  const cfgPath = path.join(root, "web", "js", "config.js");
  let cfg = {};
  if (fs.existsSync(cfgPath)) cfg = (await import(pathToFileURL(cfgPath).href)).config;
  return {
    region: process.env.TRYOUT_REGION || cfg.region || "ca-central-1",
    userPoolId: process.env.TRYOUT_USER_POOL_ID || cfg.userPoolId,
    userPoolClientId: process.env.TRYOUT_CLIENT_ID || cfg.userPoolClientId,
    graphqlUrl: process.env.TRYOUT_GRAPHQL_URL || cfg.graphqlUrl,
    appUrl: process.env.TRYOUT_APP_URL || cfg.appUrl,
  };
}

async function idp(region, action, body) {
  const res = await fetch(`https://cognito-idp.${region}.amazonaws.com/`, {
    method: "POST",
    headers: { "content-type": "application/x-amz-json-1.1", "x-amz-target": `AWSCognitoIdentityProviderService.${action}` },
    body: JSON.stringify(body),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`${String(data.__type || "").split("#").pop() || action}: ${data.message || data.Message || "failed"}`);
  return data;
}

/** Resolves to the Cognito ID token (JWT). The account needs a permanent password (scripts/create-user.sh --password). */
export async function signIn({ region, userPoolClientId }, email, password) {
  const USERNAME = email.toLowerCase();
  let r = await idp(region, "InitiateAuth", { AuthFlow: "USER_AUTH", ClientId: userPoolClientId, AuthParameters: { USERNAME, PASSWORD: password, PREFERRED_CHALLENGE: "PASSWORD" } });
  if (r.ChallengeName === "SELECT_CHALLENGE") {
    r = await idp(region, "RespondToAuthChallenge", { ClientId: userPoolClientId, ChallengeName: "SELECT_CHALLENGE", Session: r.Session, ChallengeResponses: { USERNAME, ANSWER: "PASSWORD", PASSWORD: password } });
  }
  if (r.ChallengeName === "NEW_PASSWORD_REQUIRED") throw new Error("Account still has a temporary password; sign in once in the browser first or use create-user.sh --password");
  if (!r.AuthenticationResult) throw new Error(`Unexpected challenge ${r.ChallengeName}`);
  return r.AuthenticationResult.IdToken;
}

export async function gql(graphqlUrl, idToken, query, variables = {}) {
  const res = await fetch(graphqlUrl, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: idToken },
    body: JSON.stringify({ query, variables }),
  });
  const body = await res.json();
  if (body.errors?.length) throw new Error(body.errors.map((e) => e.message).join("; "));
  return body.data;
}
