#!/usr/bin/env node
// Generates web/js/config.js from the CDK outputs file. Used by scripts/deploy.sh.
import * as fs from "node:fs";

const [outputsPath, targetPath] = process.argv.slice(2);
if (!outputsPath || !targetPath) {
  console.error("usage: write-config.js <infra/outputs.json> <web/js/config.js>");
  process.exit(2);
}
const outputs = JSON.parse(fs.readFileSync(outputsPath, "utf8"));
const stack = outputs.TryoutEvaluator || Object.values(outputs)[0];
const required = ["UserPoolId", "UserPoolClientId", "GraphqlUrl", "Region", "CloudFrontUrl"];
for (const k of required) if (!stack[k]) { console.error(`missing output ${k}`); process.exit(1); }

const config = {
  region: stack.Region,
  userPoolId: stack.UserPoolId,
  userPoolClientId: stack.UserPoolClientId,
  graphqlUrl: stack.GraphqlUrl,
  appUrl: stack.CloudFrontUrl,
};
fs.writeFileSync(
  targetPath,
  `// Generated by scripts/deploy.sh from the CDK stack outputs. Do not edit; do not commit.\n` +
  `export const config = ${JSON.stringify(config, null, 2)};\n`,
);
console.log(`wrote ${targetPath}`);
